version: '2'

networks:
  test:

services:
  db:
    image: postgres:11
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - test
      

  timescale-pg-11:
    image: timescale/timescaledb:latest-pg11
    container_name: timescale-pg-11
    ports:
      - "0.0.0.0:5112:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hybrid
    volumes:
      - $HOME/docker/volumes/timescale-pg-11/var/lib/postgresql/data:/var/lib/postgresql/data
    
    networks:
      - test
